/**
 * Códigos de error estandarizados
 * Formato: ERR_[CATEGORIA]_[ESPECIFICO]
 */

const ErrorCodes = {
  AUTH: {
    INVALID: 'ERR_AUTH_INVALID',
    EXPIRED: 'ERR_AUTH_EXPIRED',
    UNAUTHORIZED: 'ERR_AUTH_UNAUTHORIZED',
    FORBIDDEN: 'ERR_AUTH_FORBIDDEN',
    TOKEN_MISSING: 'ERR_AUTH_TOKEN_MISSING'
  },
  VALID: {
    REQUIRED: 'ERR_VALID_REQUIRED',
    INVALID_FORMAT: 'ERR_VALID_INVALID_FORMAT',
    OUT_OF_RANGE: 'ERR_VALID_OUT_OF_RANGE',
    DUPLICATE: 'ERR_VALID_DUPLICATE'
  },
  DB: {
    NOT_FOUND: 'ERR_DB_NOTFOUND',
    CONNECTION: 'ERR_DB_CONNECTION',
    QUERY: 'ERR_DB_QUERY',
    CONSTRAINT: 'ERR_DB_CONSTRAINT'
  },
  NET: {
    TIMEOUT: 'ERR_NET_TIMEOUT',
    CONNECTION: 'ERR_NET_CONNECTION',
    UNREACHABLE: 'ERR_NET_UNREACHABLE'
  },
  SYS: {
    INTERNAL: 'ERR_SYS_INTERNAL',
    UNAVAILABLE: 'ERR_SYS_UNAVAILABLE',
    MAINTENANCE: 'ERR_SYS_MAINTENANCE'
  },
  BIZ: {
    INSUFFICIENT_FUNDS: 'ERR_BIZ_INSUFFICIENT_FUNDS',
    OPERATION_NOT_ALLOWED: 'ERR_BIZ_OPERATION_NOT_ALLOWED',
    LIMIT_EXCEEDED: 'ERR_BIZ_LIMIT_EXCEEDED'
  }
};

module.exports = { ErrorCodes };
